var clusterTemplate = {};

clusterTemplate.Health = [
    '<a id="clusterHealthButton" class="btn btn-<%- statusClass %> " rel="popRight" data-trigger="hover"',
    'data-content="集群状况: <span class=\'label label-<%- statusClassLabel %>\'><%- statusText %></span>" data-html="true"',
    'href="#cluster" role="button">',
    '<i class="icon-info-sign"></i> <%- cluster_name %></a>'
].join("\n");

clusterTemplate.HealthDescribe = [
    //'<div class="row-fluid" style="padding: 15px;">',
    '<div class="well">',
    '<div class="span2 pull-left"><a href="#refreshCluster" class="btn btn-mini"  rel="tipRight" data-placement="bottom" data-html="true" data-title="每 <%- polling/1000 %> 秒更新。<br/>点击立刻更新"><i class="icon-refresh"></i> <%- lastUpdateTime %></a></div>',
    '<div class="text-center span8"><span style="font-size: 28px;">集群总览</span></div>',
    '<div class="pull-right">',
    '<a href="#visualize" class="btn btn-info" rel="tipRight" data-placement="bottom" data-html="true" data-title="浏览集群图示">',
    '<i class="icon-sitemap"></i></a>',
    '</div>',
    '</div>',

    '<div class="row-fluid">',

    '<div class="grid" style="margin-top: 10px;">',
    '<div class="grid-title">',
    '<div class="pull-left">',
    '<div class="icon-title"><i class="icon-bar-chart"></i></div>',
    '<span>集群数据信息</span>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="grid-content overflow">',

    '<div class="row-fluid center-table">',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- numeral(health.number_of_nodes).format("0,0") %></span><span>节点数</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- numeral(indices.shards.total).format("0,0") %></span><span>总分片数</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- numeral(indices.shards.successful).format("0,0") %></span><span>有效分片数</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- numeral(indices.count).format("0,0") %></span><span>索引数</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- numeral(indices.docs.count).format("0,0") %></span><span>文件数</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- numeral(indices.store.size_in_bytes).format("0.0b") %></span><span>数据大小</span>',
    '</div></div>',
    '</div>',
    '<div class="clear"></div>',
    '</div>',
    /*    '<div class="grid-content">',
     '<div class="clear"></div>',
     '<div class="clearfix"></div>',
     '</div>',*/
    '</div>', // grid

    '</div>', // row
    '<div class="row-fluid">',
    '<div class="span6">',
    '<div class="grid">',
    '<div class="grid-title">',
    '<div class="pull-left">',
    '<div class="icon-title"><i class="icon-ambulance"></i></div>',
    '<span>集群健康状况</span>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="grid-content overflow">',

    '<table class="table table-striped table-hover table-bordered  center-table">',
    '<tr>',
    '<td>状态</td>',
    '<td><span class="label label-<%- health.statusClassLabel %>"><%- health.statusText %></span></td>',
    '</tr>',
    '<tr>',
    '<td>是否超时?</td>',
    '<td><%- health.timed_out %></td>',
    '</tr>',
    '<tr>',
    '<td>节点数</td>',
    '<td><%- numeral(health.number_of_nodes).format("0,0") %></td>',
    '</tr>',
    '<tr>',
    '<td>数据节点数</td>',
    '<td><%- numeral(health.number_of_data_nodes).format("0,0") %></td>',
    '</tr>',
    '<tr>',
    '<td>活跃原始分片数</td>',
    '<td><%- numeral(health.active_primary_shards).format("0,0") %></td>',
    '</tr>',
    '<tr>',
    '<td>活跃分片数</td>',
    '<td><%- numeral(health.active_shards).format("0,0") %></td>',
    '</tr>',
    '<tr>',
    '<td>重新分配分片数</td>',
    '<td><%- numeral(health.relocating_shards).format("0,0") %></td>',
    '</tr>',
    '<tr>',
    '<td>初始化分片数</td>',
    '<td><%- numeral(health.initializing_shards).format("0,0") %></td>',
    '</tr>',
    '<tr>',
    '<td>未分配分片数</td>',
    '<td><%- numeral(health.unassigned_shards).format("0,0") %></td>',
    '</tr>',
    '</table>',

    '<div class="clear"></div>',
    '</div>',
    '<div class="grid-content">',
    '<div class="clear"></div>',
    '<div class="clearfix"></div>',
    '</div>',
    '</div>',

    '</div>', // span

    '<div class="span6">',
    '<div class="grid">',
    '<div class="grid-title">',
    '<div class="pull-left">',
    '<div class="icon-title"><i class="icon-list"></i></div>',
    '<span>索引</span>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="grid-content overflow">',
    '<% if (!jQuery.isEmptyObject(indices.indices)) { %>',
    '<table class="table table-bordered table-striped table-hover" id="indicesTable">',
    '<thead>',
    '<tr><th>Index</th><th># Docs</th><th>数据大小</th><th># Shards</th><th># Replicas</th><th>Status</th></tr>',
    '</thead>',
    '<tbody>',
    '<% _.each(indices.indices.sort(function(a,b) {return (a.name > b.name) ? -1 : ((b.name > a.name) ? 11 : 0);} ), function(index) { %>',
    '<tr><td>',
    '<a href="#index/<%- index.id %>"  rel="tipRight" data-placement="bottom" data-title="Index Information"><%- index.name %></a>',
    '</td><td><%- numeral(index.primaries.docs.count).format("0,0") %></td><td><%- numeral(index.primaries.store.size_in_bytes).format("0.0b")  %></td>',
    '<td><%- numeral(index.numshards).format("0,0") %></td><td><%- numeral(index.numreplicas).format("0,0") %></td><td><%- index.status %></td></tr>',
    '<% }); %>',
    '</tbody>',
    '</table>',
    '<% } %>',

    '<div class="clear"></div>',
    '</div>',
    '<div class="grid-content">',
    '<div class="clear"></div>',
    '<div class="clearfix"></div>',
    '</div>',
    '</div>',
    '</div>'
].join("\n");
